name: Build application

on: [push, pull_request]

jobs:
 windows-msvc-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Tables
      shell: bash
      run: |
        export CMAKE_BUILD_PARALLEL_LEVEL=4
        mkdir build
        cmake \
            -A x64 \
            -B ${PWD}/build
        cmake --build ${PWD}/build --config Release
    - name: Run tests
      shell: bash
      run: |
        ${PWD}/build/test/Release/tables_test.exe --gtest_repeat=2 --gtest_break_on_failure
